// <auto-generated />
using System;
using CreditRisk.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditRisk.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditRisk.API.Models.AnalysisLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("CompositeScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double>("LoanAmount")
                        .HasColumnType("float");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnalysisLogs");
                });

            modelBuilder.Entity("CreditRisk.API.Models.Applicant", b =>
                {
                    b.Property<Guid>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreteadAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DebtToIncomeRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("EmployementYears")
                        .HasColumnType("float");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ApplicantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("CreditRisk.API.Models.LearnContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RealExample")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsedIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LearnContents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Abbr = "SR",
                            Category = "Risk-Adjusted Return",
                            Explanation = "If two investments have the same return, the one with lower volatility has a higher Sharpe Ratio. A Sharpe above 1.0 is generally considered good. Above 2.0 is exceptional.",
                            Formula = "Sharpe = (Portfolio Return - Risk-Free Rate) / Std Dev of Returns",
                            IsActive = true,
                            ModelName = "Sharpe Ratio",
                            RealExample = "A loan at 9% interest with 12% return volatility and a 4% risk-free rate has a Sharpe of (0.09 - 0.04) / 0.12 = 0.42. That is poor.",
                            SortOrder = 1,
                            Summary = "Measures how much extra return you earn per unit of risk taken.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Loan Analysis, Portfolio Comparison"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Abbr = "C",
                            Category = "Risk-Return Model",
                            Explanation = "Beta measures how sensitive an asset is to market movements. A salaried employee has low beta. A business owner has high beta. CAPM tells you what return you should demand.",
                            Formula = "Expected Return = Risk-Free Rate + Beta x (Market Return - Risk-Free Rate)",
                            IsActive = true,
                            ModelName = "CAPM",
                            RealExample = "A self-employed borrower with Beta 1.2, market return 12%, risk-free rate 6.5% needs a return of 6.5% + 1.2 x (12% - 6.5%) = 13.1%.",
                            SortOrder = 2,
                            Summary = "Calculates the minimum return an investment must earn given its market risk.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Loan Analysis"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Abbr = "KC",
                            Category = "Optimal Bet Sizing",
                            Explanation = "In lending, winning means the loan gets repaid with interest. Kelly tells a lender how much of their total capital should go into any single loan. Professional investors almost always use Half-Kelly for safety.",
                            Formula = "Kelly = (Win Probability x Win Ratio - Loss Probability) / Win Ratio",
                            IsActive = true,
                            ModelName = "Kelly Criterion",
                            RealExample = "If repayment probability is 92% and interest earned is 9% of principal, Kelly fraction is approximately 3% of capital per loan.",
                            SortOrder = 3,
                            Summary = "Tells you what fraction of your capital to allocate to maximise long-term growth.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Loan Analysis, Portfolio Comparison"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Abbr = "VaR",
                            Category = "Portfolio Loss Metric",
                            Explanation = "VaR answers: what is the worst-case loss we expect 95% of the time over the next 30 days? Banks use VaR daily to manage risk exposure across entire portfolios.",
                            Formula = "VaR = Loan Amount x Volatility x Z-score x sqrt(Days / 252)",
                            IsActive = true,
                            ModelName = "Value at Risk",
                            RealExample = "A 5,00,000 loan with 15% annual volatility has a 30-day 95% VaR of approximately 35,826. You should not lose more than this in any 30-day period with 95% confidence.",
                            SortOrder = 4,
                            Summary = "The maximum loss you can expect with a given confidence level over a time period.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Loan Analysis"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Abbr = "GBM",
                            Category = "Price Process Model",
                            Explanation = "GBM is the same mathematics used to model stock prices. Applied to lending it simulates 1000 possible futures for an applicant income. If many paths fall below the minimum repayment threshold the loan is high stress-risk.",
                            Formula = "S(t+1) = S(t) x exp((mu - sigma^2/2) x dt + sigma x sqrt(dt) x Z)",
                            IsActive = true,
                            ModelName = "Geometric Brownian Motion",
                            RealExample = "A borrower earning 8L per year with 15% income volatility — GBM simulates their income over 5 years. If 18% of paths drop below 5L minimum needed to repay, stress probability is 18%.",
                            SortOrder = 5,
                            Summary = "Models how income or asset prices evolve randomly over time.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "NAV Simulator"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            Abbr = "BS",
                            Category = "Option Pricing Model",
                            Explanation = "In lending a borrower right to prepay is a financial option. When interest rates fall borrowers refinance. Black-Scholes quantifies exactly how much that prepayment right is worth — a cost to the lender in lost future interest.",
                            Formula = "Call = S x N(d1) - K x e^(-rT) x N(d2)",
                            IsActive = true,
                            ModelName = "Black-Scholes",
                            RealExample = "A 5,00,000 loan at 9% for 5 years has a prepayment option worth approximately 28,000 if volatility is 20%. The lender should demand slightly higher interest to compensate.",
                            SortOrder = 6,
                            Summary = "Prices the value of a financial option — the right but not obligation to do something.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Loan Analysis, Portfolio Comparison"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            Abbr = "MV",
                            Category = "Portfolio Optimization",
                            Explanation = "Introduced by Harry Markowitz in 1952. Shows that diversification mathematically reduces risk without sacrificing return. The Efficient Frontier is the curve of all optimal portfolios.",
                            Formula = "Minimise w'Sigma*w subject to w'mu = target return",
                            IsActive = true,
                            ModelName = "Mean-Variance Optimization",
                            RealExample = "A portfolio of 60% home loans and 40% personal loans might have lower combined volatility than either loan type alone because their defaults do not perfectly correlate.",
                            SortOrder = 7,
                            Summary = "Finds the ideal mix of assets that maximises return for a given level of risk.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Admin Portfolio Dashboard"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            Abbr = "M",
                            Category = "Default Distance",
                            Explanation = "Robert Merton showed that equity is mathematically a call option on assets. If assets fall below total debt default occurs. Distance to Default measures this in standard deviations — higher is safer.",
                            Formula = "Distance to Default = (ln(A/D) + (r - sigma^2/2) x T) / (sigma x sqrt(T))",
                            IsActive = true,
                            ModelName = "Merton Model",
                            RealExample = "A borrower with 12L in assets and 5L in debt with 15% asset volatility has a Distance to Default of 2.8 standard deviations. Default probability is approximately 2.5%.",
                            SortOrder = 8,
                            Summary = "Treats a borrower assets as a stock — estimates how far they are from defaulting.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Loan Analysis"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000009"),
                            Abbr = "SIP",
                            Category = "Investment Planning",
                            Explanation = "SIP is the most common way Indians invest in mutual funds. By investing a fixed amount every month you buy more units when prices are low. The power of compounding means small regular investments grow into large corpuses over time.",
                            Formula = "FV = P x [((1 + r)^n - 1) / r] x (1 + r)",
                            IsActive = true,
                            ModelName = "SIP Calculator",
                            RealExample = "Investing 5,000 per month for 10 years at 12% annual return gives a corpus of 11.6L on an investment of just 6L — a wealth gain of 5.6L.",
                            SortOrder = 9,
                            Summary = "Calculates how a fixed monthly investment grows into a corpus over time.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Investment Hub"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000010"),
                            Abbr = "CAGR",
                            Category = "Growth Rate",
                            Explanation = "Absolute return tells you the total gain. CAGR tells you the annual rate at which that gain compounded. All mutual fund fact sheets in India are required to report CAGR.",
                            Formula = "CAGR = (Final Value / Initial Value) ^ (1 / Years) - 1",
                            IsActive = true,
                            ModelName = "CAGR",
                            RealExample = "1,00,000 growing to 2,50,000 in 7 years has an absolute return of 150% but a CAGR of 13.98% per year.",
                            SortOrder = 10,
                            Summary = "The true annualised growth rate of an investment accounting for compounding.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Investment Hub"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000011"),
                            Abbr = "NAV",
                            Category = "Fund Analysis",
                            Explanation = "NAV is the price of one unit of a mutual fund. Our simulator runs 500 GBM paths to show the range of possible outcomes — bull case, expected median, and bear case.",
                            Formula = "Uses Geometric Brownian Motion with fund-specific drift and volatility",
                            IsActive = true,
                            ModelName = "NAV Tracker",
                            RealExample = "A fund starting at NAV 10 with 12% expected return and 18% volatility over 5 years shows Bull case 28, Expected 18, Bear case 11.",
                            SortOrder = 11,
                            Summary = "Simulates how a mutual fund NAV might evolve using Monte Carlo methods.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Investment Hub"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000012"),
                            Abbr = "SVL",
                            Category = "Comparison Tool",
                            Explanation = "The core question for any capital allocator: given a sum of money should I lend it or invest it? This tool answers using Sharpe Ratios — whichever gives more return per unit of risk is the better choice.",
                            Formula = "Loan Effective Return = Interest Rate x (1 - Default Probability)",
                            IsActive = true,
                            ModelName = "SIP vs Loan",
                            RealExample = "5,00,000 as a 9% loan with 8% default risk has Sharpe 0.55. Same amount in a fund at 12% return and 18% volatility has Sharpe 0.44. The loan wins on risk-adjusted terms.",
                            SortOrder = 12,
                            Summary = "Compares deploying capital as a loan versus investing it in a mutual fund using Sharpe Ratios.",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsedIn = "Compare Tool"
                        });
                });

            modelBuilder.Entity("CreditRisk.API.Models.LoanApplication", b =>
                {
                    b.Property<Guid>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("LoanAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("CreditRisk.API.Models.RiskScore", b =>
                {
                    b.Property<Guid>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactorsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ScoredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScoreId");

                    b.HasIndex("LoanId");

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("CreditRisk.API.Models.LoanApplication", b =>
                {
                    b.HasOne("CreditRisk.API.Models.Applicant", "Applicant")
                        .WithMany("LoanApplications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("CreditRisk.API.Models.RiskScore", b =>
                {
                    b.HasOne("CreditRisk.API.Models.LoanApplication", "LoanApplication")
                        .WithMany("RiskScores")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanApplication");
                });

            modelBuilder.Entity("CreditRisk.API.Models.Applicant", b =>
                {
                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("CreditRisk.API.Models.LoanApplication", b =>
                {
                    b.Navigation("RiskScores");
                });
#pragma warning restore 612, 618
        }
    }
}
